services:
  postgres:
    image: postgres:17.5
    container_name: tokasa_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
    - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres

volumes:
  postgres-data:
